#!/usr/bin/env python3
"""Audit Parliament search-result pages against exported listings and manifest.

This uses the same query parameters generated by the listing-page search bars,
then pages through the visible search results:
  - Acts: ?year=YYYY&itemCount=16&page=N
  - Government Bills: ?year=YYYY&itemCount=16&page=N

The goal is to catch rows present in the UI search results but absent from the
CSV endpoints or local manifest, and vice versa.
"""

from __future__ import annotations

import argparse
import csv
import html
import json
import re
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import urlencode
from urllib.request import Request, urlopen


PROJECT_ROOT = Path(__file__).resolve().parents[1]
RAW_ROOT = PROJECT_ROOT / "data" / "raw" / "official" / "parliament" / "search_pages"
MANIFEST_DIR = PROJECT_ROOT / "data" / "manifests"
DOCUMENT_MANIFEST_PATH = MANIFEST_DIR / "document_manifest.csv"
REPORT_CSV_PATH = MANIFEST_DIR / "parliament_search_ui_audit.csv"
REPORT_JSON_PATH = MANIFEST_DIR / "parliament_search_ui_audit.json"
RUN_LOG_PATH = MANIFEST_DIR / "extraction_run_log.csv"
USER_AGENT = "SL-Legal-Assist-Parliament-Search-UI-Audit/0.1"


@dataclass(frozen=True)
class ListingConfig:
    source_id: str
    document_type: str
    page_url: str
    csv_url: str
    detail_path: str
    raw_dir: str
    number_header: str
    title_header: str
    date_header: str
    detail_header: str
    number_query: str


CONFIGS = {
    "acts": ListingConfig(
        source_id="PARL_ACTS",
        document_type="Act",
        page_url="https://www.parliament.lk/en/business-of-parliament/acts-listing",
        csv_url="https://www.parliament.lk/en/business-of-parliament/download-acts-listing/csv",
        detail_path="/act-details/",
        raw_dir="acts",
        number_header="Act No.",
        title_header="Act Title",
        date_header="Endorsed Date",
        detail_header="Link to Act",
        number_query="actNo",
    ),
    "government_bills": ListingConfig(
        source_id="PARL_GOV_BILLS",
        document_type="Government Bill",
        page_url="https://www.parliament.lk/en/business-of-parliament/government-bills-listing",
        csv_url="https://www.parliament.lk/en/business-of-parliament/download-bills-listing/csv",
        detail_path="/bill-details/",
        raw_dir="government_bills",
        number_header="Bill No.",
        title_header="Bill Title",
        date_header="Presented Date",
        detail_header="Link to Bill",
        number_query="billNo",
    ),
}


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def read_csv(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def write_csv(path: Path, fields: list[str], rows: list[dict[str, str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)


def append_run_log(row: dict[str, str]) -> None:
    rows = read_csv(RUN_LOG_PATH)
    fields = list(rows[0].keys()) if rows else [
        "run_id",
        "source_id",
        "run_type",
        "started_at",
        "ended_at",
        "documents_found",
        "documents_downloaded",
        "errors",
        "new_missing_items",
        "notes",
    ]
    rows.append(row)
    write_csv(RUN_LOG_PATH, fields, rows)


def fetch_text(url: str, timeout: int) -> str:
    req = Request(url, headers={"User-Agent": USER_AGENT})
    with urlopen(req, timeout=timeout) as response:
        return response.read().decode("utf-8-sig", errors="replace")


def csv_rows_for_year(config: ListingConfig, year: int, timeout: int) -> list[dict[str, str]]:
    params = {"year": str(year)}
    if config.source_id == "PARL_GOV_BILLS":
        params["billType"] = "G"
    text = fetch_text(f"{config.csv_url}?{urlencode(params)}", timeout)
    return [
        row
        for row in csv.DictReader(text.splitlines())
        if row.get(config.number_header) or row.get(config.title_header)
    ]


def search_page_url(config: ListingConfig, year: int, page: int) -> str:
    params = {"year": str(year), "itemCount": "16"}
    if page > 1:
        params["page"] = str(page)
    return f"{config.page_url}?{urlencode(params)}"


def clean_text(value: str) -> str:
    value = re.sub(r"<[^>]+>", " ", value)
    value = html.unescape(value)
    value = re.sub(r"\s+", " ", value)
    return value.strip()


def source_document_id(url: str) -> str:
    match = re.search(r"/(?:act|bill)-details/([GP][0-9]+)", url)
    return match.group(1) if match else ""


def parse_search_results(page_html: str, config: ListingConfig, year: int) -> list[dict[str, str]]:
    results = []
    heading_pattern = re.compile(
        r"<a\s+href='(https://www\.parliament\.lk/en/business-of-parliament/"
        + re.escape(config.detail_path.strip("/"))
        + r"/[GP][0-9]+)'\s*>\s*<h1 class='sub_heading'>(.*?)</h1>\s*</a>",
        re.DOTALL,
    )
    matches = list(heading_pattern.finditer(page_html))
    for index, match in enumerate(matches):
        detail_url = match.group(1)
        heading = clean_text(match.group(2))
        segment_end = matches[index + 1].start() if index + 1 < len(matches) else len(page_html)
        segment = page_html[match.end() : segment_end]
        pdf_match = re.search(
            r"href='(https://www\.parliament\.lk/uploads/(?:acts|bills)/(?:g|p)bills/english/[0-9]+\.pdf)'",
            segment,
        )
        number = ""
        title = heading
        number_match = re.match(r"\s*0*([0-9]+)(?:\s*/\s*[0-9]{4})?\s*:\s*(.*)", heading)
        if number_match:
            number = str(int(number_match.group(1)))
            title = number_match.group(2).strip()
        date_match = re.search(r"(?:Endorsed|Presented) Date:\s*([0-9]{4}-[0-9]{2}-[0-9]{2})", segment)
        results.append(
            {
                "source_id": config.source_id,
                "document_type": config.document_type,
                "year": str(year),
                "number": number,
                "title": title,
                "date": date_match.group(1) if date_match else "",
                "source_document_id": source_document_id(detail_url),
                "source_url": detail_url,
                "search_pdf_url": pdf_match.group(1) if pdf_match else "",
            }
        )
    return results


def fetch_search_results_for_year(
    config: ListingConfig,
    year: int,
    expected_count: int,
    timeout: int,
    save_html: bool,
) -> list[dict[str, str]]:
    if expected_count == 0:
        # Still touch page 1 for years exposed by the search control but empty.
        pages = 1
    else:
        pages = (expected_count + 15) // 16
    all_results = []
    raw_dir = RAW_ROOT / config.raw_dir / str(year)
    for page in range(1, pages + 1):
        url = search_page_url(config, year, page)
        page_html = fetch_text(url, timeout)
        if save_html:
            raw_dir.mkdir(parents=True, exist_ok=True)
            (raw_dir / f"page_{page:03d}.html").write_text(page_html, encoding="utf-8")
        all_results.extend(parse_search_results(page_html, config, year))
    return all_results


def row_key(row: dict[str, str]) -> str:
    if row.get("source_document_id"):
        return row["source_document_id"]
    url = row.get("source_url") or row.get("Link to Act") or row.get("Link to Bill") or ""
    source_id = source_document_id(url)
    if source_id:
        return source_id
    return f"{row.get('year') or row.get('Bill Year') or row.get('Act Year')}:{row.get('number') or row.get('Act No.') or row.get('Bill No.')}:{row.get('title') or row.get('Act Title') or row.get('Bill Title')}"


def normalize_csv_row(row: dict[str, str], config: ListingConfig) -> dict[str, str]:
    source_url = (row.get(config.detail_header) or "").strip()
    year = (row.get("Bill Year") or row.get("Act Year") or "").strip()
    if not year:
        year_match = re.search(r"/([0-9]{4})$", row.get(config.number_header, ""))
        year = year_match.group(1) if year_match else ""
    return {
        "source_id": config.source_id,
        "document_type": config.document_type,
        "year": year,
        "number": str(int(row.get(config.number_header, "0").strip())) if row.get(config.number_header, "").strip().isdigit() else row.get(config.number_header, "").strip(),
        "title": (row.get(config.title_header) or "").strip(),
        "date": (row.get(config.date_header) or "").strip(),
        "source_document_id": source_document_id(source_url),
        "source_url": source_url,
    }


def audit_config(config: ListingConfig, start_year: int, end_year: int, timeout: int, save_html: bool) -> dict[str, object]:
    manifest_rows = []
    for row in read_csv(DOCUMENT_MANIFEST_PATH):
        if row.get("source_id") != config.source_id or row.get("document_type") != config.document_type:
            continue
        try:
            row_year = int(row.get("year", "0"))
        except ValueError:
            continue
        if start_year <= row_year <= end_year:
            manifest_rows.append(row)
    manifest_keys = {row_key(row) for row in manifest_rows}

    csv_all = []
    search_all = []
    errors = []
    year_summaries = []
    diff_rows = []

    for year in range(start_year, end_year + 1):
        try:
            csv_year = [normalize_csv_row(row, config) for row in csv_rows_for_year(config, year, timeout)]
            search_year = fetch_search_results_for_year(config, year, len(csv_year), timeout, save_html)
        except Exception as exc:
            errors.append(f"{config.source_id} {year}: {type(exc).__name__}: {exc}")
            continue

        csv_keys = {row_key(row) for row in csv_year}
        search_keys = {row_key(row) for row in search_year}
        csv_all.extend(csv_year)
        search_all.extend(search_year)
        missing_from_search = sorted(csv_keys - search_keys)
        missing_from_csv = sorted(search_keys - csv_keys)
        year_summaries.append(
            {
                "source_id": config.source_id,
                "year": str(year),
                "csv_count": str(len(csv_year)),
                "search_ui_count": str(len(search_year)),
                "missing_from_search_count": str(len(missing_from_search)),
                "missing_from_csv_count": str(len(missing_from_csv)),
            }
        )
        for key in missing_from_search:
            match = next((row for row in csv_year if row_key(row) == key), {})
            diff_rows.append(
                {
                    "source_id": config.source_id,
                    "year": str(year),
                    "issue": "csv_row_missing_from_search_ui",
                    "source_document_id": key,
                    "number": match.get("number", ""),
                    "title": match.get("title", ""),
                    "source_url": match.get("source_url", ""),
                }
            )
        for key in missing_from_csv:
            match = next((row for row in search_year if row_key(row) == key), {})
            diff_rows.append(
                {
                    "source_id": config.source_id,
                    "year": str(year),
                    "issue": "search_ui_row_missing_from_csv",
                    "source_document_id": key,
                    "number": match.get("number", ""),
                    "title": match.get("title", ""),
                    "source_url": match.get("source_url", ""),
                }
            )

    csv_keys_all = {row_key(row) for row in csv_all}
    search_keys_all = {row_key(row) for row in search_all}
    missing_from_manifest = sorted((csv_keys_all | search_keys_all) - manifest_keys)
    manifest_extra = sorted(manifest_keys - (csv_keys_all | search_keys_all))
    for key in missing_from_manifest:
        match = next((row for row in csv_all + search_all if row_key(row) == key), {})
        diff_rows.append(
            {
                "source_id": config.source_id,
                "year": match.get("year", ""),
                "issue": "listing_row_missing_from_manifest",
                "source_document_id": key,
                "number": match.get("number", ""),
                "title": match.get("title", ""),
                "source_url": match.get("source_url", ""),
            }
        )
    for key in manifest_extra:
        match = next((row for row in manifest_rows if row_key(row) == key), {})
        diff_rows.append(
            {
                "source_id": config.source_id,
                "year": match.get("year", ""),
                "issue": "manifest_row_not_seen_in_listing",
                "source_document_id": key,
                "number": match.get("number", ""),
                "title": match.get("title", ""),
                "source_url": match.get("source_url", ""),
            }
        )

    return {
        "source_id": config.source_id,
        "csv_count": len(csv_all),
        "search_ui_count": len(search_all),
        "manifest_count": len(manifest_rows),
        "csv_unique": len(csv_keys_all),
        "search_ui_unique": len(search_keys_all),
        "manifest_unique": len(manifest_keys),
        "missing_from_manifest": len(missing_from_manifest),
        "manifest_extra": len(manifest_extra),
        "diff_rows": diff_rows,
        "year_summaries": year_summaries,
        "errors": errors,
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Audit Parliament listing search UI.")
    parser.add_argument("--start-year", type=int, default=1948)
    parser.add_argument("--end-year", type=int, default=datetime.now().year)
    parser.add_argument("--timeout", type=int, default=20)
    parser.add_argument("--save-html", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    started = utc_now()
    results = []
    diff_rows = []
    year_rows = []
    errors = []
    for config in CONFIGS.values():
        result = audit_config(config, args.start_year, args.end_year, args.timeout, args.save_html)
        results.append({k: v for k, v in result.items() if k not in {"diff_rows", "year_summaries"}})
        diff_rows.extend(result["diff_rows"])
        year_rows.extend(result["year_summaries"])
        errors.extend(result["errors"])

    REPORT_JSON_PATH.write_text(
        json.dumps(
            {
                "started_at": started,
                "ended_at": utc_now(),
                "start_year": args.start_year,
                "end_year": args.end_year,
                "results": results,
                "diff_count": len(diff_rows),
                "errors": errors,
            },
            indent=2,
            ensure_ascii=False,
        ),
        encoding="utf-8",
    )
    write_csv(
        REPORT_CSV_PATH,
        ["source_id", "year", "issue", "source_document_id", "number", "title", "source_url"],
        diff_rows,
    )
    write_csv(
        MANIFEST_DIR / "parliament_search_ui_year_counts.csv",
        [
            "source_id",
            "year",
            "csv_count",
            "search_ui_count",
            "missing_from_search_count",
            "missing_from_csv_count",
        ],
        year_rows,
    )
    append_run_log(
        {
            "run_id": "run_" + started.replace(":", "").replace("-", "").replace("+", "z") + "_search_ui_audit",
            "source_id": "PARL_SEARCH_UI",
            "run_type": "search_ui_audit",
            "started_at": started,
            "ended_at": utc_now(),
            "documents_found": str(sum(result["search_ui_count"] for result in results)),
            "documents_downloaded": "0",
            "errors": json.dumps(errors, ensure_ascii=False),
            "new_missing_items": "",
            "notes": f"Search UI audit diff rows: {len(diff_rows)}",
        }
    )
    print(json.dumps({"results": results, "diff_count": len(diff_rows), "errors": errors}, indent=2, ensure_ascii=False))
    return 1 if errors or diff_rows else 0


if __name__ == "__main__":
    raise SystemExit(main())
